### ISSUE TITLE
Emitting or deriving trait implementations

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#886]
**Let's implement all the traits!!**

All of the "Derive `Blah` when possible" issues have code in tree already that they can crib from, so shouldn't be too difficult to write.

Once we start deriving  lots of different traits, I expect we may find that we can unify their implementations, or at least make a generic `CanDeriveTrait<T: DerivableTrait>` kind of generic thing.

------------------------------------------

* [ ] "manually" implement `Debug` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/875

* [ ] Derive `Hash` when possible: https://github.com/rust-lang-nursery/rust-bindgen/issues/876

  * [ ] "manually" implement `Hash` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/877

* [ ] Derive `PartialEq` when possible: https://github.com/rust-lang-nursery/rust-bindgen/issues/878

  * [ ] "manually" implement `PartialEq` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/879

  * [ ] Derive `Eq` when possible: https://github.com/rust-lang-nursery/rust-bindgen/issues/880

    * [ ] "manually" implement `Eq` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/881

* [ ] Derive `PartialOrd` when possible: https://github.com/rust-lang-nursery/rust-bindgen/issues/882

  * [ ] "manually" implement `PartialOrd` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/883

  * [ ] Derive `Ord` when possible: https://github.com/rust-lang-nursery/rust-bindgen/issues/884

    * [ ] "manually" implement `Ord` when we cannot derive it: https://github.com/rust-lang-nursery/rust-bindgen/issues/885

**Comment by dimbleby** [comment]
Should `Copy` be included in this meta-issue (as discussed in #934)?  It would be a real odd-man-out if not.

**Comment by fitzgen** [comment]
> Should Copy be included in this meta-issue (as discussed in #934)? It would be a real odd-man-out if not.

We already derive/impl `Clone` and `Copy` when possible, it's just that there's that caveat discussed in #934. This meta issue is for tracking traits we *don't* derive/impl yet.

**Comment by photoszzt** [comment]
@fitzgen derive Hash is implemented. But miss the mark there.

**Comment by fitzgen** [comment]
> @fitzgen derive Hash(#876) is implemented. But miss the mark there.

Fixed, thanks!

**Comment by dimbleby** [comment]
> We already derive/impl Clone and Copy when possible, it's just that there's that caveat discussed in #934. This meta issue is for tracking traits we don't derive/impl yet.

My point is that #934 says that WIBNI to derive `Copy` where possible and (only) otherwise manually implement it; and that this issue says pretty much the same thing for every other trait.  In particular, `bindgen` often does *not* derive `Copy` when it would have been possible to do so.

But I don't suppose it really matters!  Tracking that in one place is certainly enough; I was just trying to tie some loose ends together.
